const text = [
  "someone says they miss their family",
  "live show blunder",
  "someone compliments julie during live show",
  "backdoor plan",
  "someone throws a competition",
  "julie tells someone to remember they're live",
  "HOH looks at TV",
  "a pawn goes home",
  "fight/argument",
  "someone cries",
  "someone walks in on people talking",
  "julie wears an ugly outfit",
  "FREE SPACE",
  "someone gets called a floater",
  "secret comes out",
  "someone turns on their own alliance",
  "\"I have to go with the house/the HOH\"",
  "\"Who wants to see my HOH room?\"",
  "someone gets picked for POV that someone said they didn't want",
  "someone talks about making a bit move but doesn't",
  "unanimous vote",
  "final 2 deal made",
  "POV used on someone else (not to save themselves)",
  "edit tries to mislead us",
  "target wins safety",
];